-- ====================================================
-- Script Gerado Automaticamente em 2026-04-01T19:58:49.513Z
-- Execute no SQL Editor do Supabase
-- ====================================================

-- Tabela: AuditLog
ALTER TABLE public."AuditLog"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "from_balance_id" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: BOM
ALTER TABLE public."BOM"
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "quantity" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "routes" text,
  ADD COLUMN IF NOT EXISTS "selectedComponent" text,
  ADD COLUMN IF NOT EXISTS "sequence" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: BOMDeliveryControl
ALTER TABLE public."BOMDeliveryControl"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: BOMItem
ALTER TABLE public."BOMItem"
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "quantity" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "routes" text,
  ADD COLUMN IF NOT EXISTS "selectedComponent" text,
  ADD COLUMN IF NOT EXISTS "sequence" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: BOMVersion
ALTER TABLE public."BOMVersion"
  ADD COLUMN IF NOT EXISTS "quantity" text,
  ADD COLUMN IF NOT EXISTS "routes" text,
  ADD COLUMN IF NOT EXISTS "selectedComponent" text,
  ADD COLUMN IF NOT EXISTS "sequence" text;

-- Tabela: Client
ALTER TABLE public."Client"
  ADD COLUMN IF NOT EXISTS "address" text,
  ADD COLUMN IF NOT EXISTS "attachments" text,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "contact_address" text,
  ADD COLUMN IF NOT EXISTS "contact_phone" text,
  ADD COLUMN IF NOT EXISTS "credit_limit" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "document" text,
  ADD COLUMN IF NOT EXISTS "email" text,
  ADD COLUMN IF NOT EXISTS "installation_required" text,
  ADD COLUMN IF NOT EXISTS "location_address" text,
  ADD COLUMN IF NOT EXISTS "location_latitude" text,
  ADD COLUMN IF NOT EXISTS "location_longitude" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_name" text,
  ADD COLUMN IF NOT EXISTS "phone" text,
  ADD COLUMN IF NOT EXISTS "photos" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "project_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "reason_description" text,
  ADD COLUMN IF NOT EXISTS "return_date" text,
  ADD COLUMN IF NOT EXISTS "sale_date" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "seller_name" text,
  ADD COLUMN IF NOT EXISTS "serial_number" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "validity_date" text,
  ADD COLUMN IF NOT EXISTS "voltage_type" text,
  ADD COLUMN IF NOT EXISTS "warranty_months" text;

-- Tabela: Company
ALTER TABLE public."Company"
  ADD COLUMN IF NOT EXISTS "address" text,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "document" text,
  ADD COLUMN IF NOT EXISTS "email" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "phone" text,
  ADD COLUMN IF NOT EXISTS "state" text;

-- Tabela: ConfigurationHistory
ALTER TABLE public."ConfigurationHistory"
  ADD COLUMN IF NOT EXISTS "auto_apply" text,
  ADD COLUMN IF NOT EXISTS "config_id" text,
  ADD COLUMN IF NOT EXISTS "config_key" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "expected_value" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "test_type" text,
  ADD COLUMN IF NOT EXISTS "validation_rule" text;

-- Tabela: ConfigurationTest
ALTER TABLE public."ConfigurationTest"
  ADD COLUMN IF NOT EXISTS "auto_apply" text,
  ADD COLUMN IF NOT EXISTS "config_id" text,
  ADD COLUMN IF NOT EXISTS "config_key" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "expected_value" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "test_type" text,
  ADD COLUMN IF NOT EXISTS "validation_rule" text;

-- Tabela: CostCenter
ALTER TABLE public."CostCenter"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text;

-- Tabela: DailyVehicleLog
ALTER TABLE public."DailyVehicleLog"
  ADD COLUMN IF NOT EXISTS "is_company_vehicle" text,
  ADD COLUMN IF NOT EXISTS "km_end" text,
  ADD COLUMN IF NOT EXISTS "km_start" text,
  ADD COLUMN IF NOT EXISTS "log_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text;

-- Tabela: EngineeringProject
ALTER TABLE public."EngineeringProject"
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "estimated_end_date" text,
  ADD COLUMN IF NOT EXISTS "estimated_hours" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "phase" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_description" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "progress_percent" text,
  ADD COLUMN IF NOT EXISTS "responsible_name" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "type" text;

-- Tabela: EngineeringProjectItem
ALTER TABLE public."EngineeringProjectItem"
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "estimated_end_date" text,
  ADD COLUMN IF NOT EXISTS "estimated_hours" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "phase" text,
  ADD COLUMN IF NOT EXISTS "product_description" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "progress_percent" text,
  ADD COLUMN IF NOT EXISTS "responsible_name" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text;

-- Tabela: EngineeringProjectUpdate
ALTER TABLE public."EngineeringProjectUpdate"
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "estimated_end_date" text,
  ADD COLUMN IF NOT EXISTS "estimated_hours" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "phase" text,
  ADD COLUMN IF NOT EXISTS "product_description" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "progress_percent" text,
  ADD COLUMN IF NOT EXISTS "responsible_name" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text;

-- Tabela: InventoryCount
ALTER TABLE public."InventoryCount"
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text;

-- Tabela: InventoryCountItem
ALTER TABLE public."InventoryCountItem"
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text;

-- Tabela: InventoryMove
ALTER TABLE public."InventoryMove"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "carrier" text,
  ADD COLUMN IF NOT EXISTS "category" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "cost_price" text,
  ADD COLUMN IF NOT EXISTS "from_balance_id" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "max_stock" text,
  ADD COLUMN IF NOT EXISTS "min_stock" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "nf_number" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "sale_price" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "sku" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "volume" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "weight" text;

-- Tabela: Location
ALTER TABLE public."Location"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "barcode" text,
  ADD COLUMN IF NOT EXISTS "capacity" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "from_balance_id" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "modulo" text,
  ADD COLUMN IF NOT EXISTS "nivel" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "posicao" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "rua" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: MaterialRequest
ALTER TABLE public."MaterialRequest"
  ADD COLUMN IF NOT EXISTS "department" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "needed_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "requester" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text;

-- Tabela: MaterialRequestItem
ALTER TABLE public."MaterialRequestItem"
  ADD COLUMN IF NOT EXISTS "department" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "needed_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "requester" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text;

-- Tabela: Notification
ALTER TABLE public."Notification"
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "end_time" text,
  ADD COLUMN IF NOT EXISTS "is_company_vehicle" text,
  ADD COLUMN IF NOT EXISTS "next_action" text,
  ADD COLUMN IF NOT EXISTS "next_visit_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "proposal_sent" text,
  ADD COLUMN IF NOT EXISTS "prospective_client_name" text,
  ADD COLUMN IF NOT EXISTS "result" text,
  ADD COLUMN IF NOT EXISTS "start_time" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "visit_date" text,
  ADD COLUMN IF NOT EXISTS "visit_report" text,
  ADD COLUMN IF NOT EXISTS "visit_type" text;

-- Tabela: PaymentCondition
ALTER TABLE public."PaymentCondition"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_name" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "seller_name" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "validity_date" text;

-- Tabela: Product
ALTER TABLE public."Product"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "category" text,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "condition" text,
  ADD COLUMN IF NOT EXISTS "contact_address" text,
  ADD COLUMN IF NOT EXISTS "contact_phone" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "cost_price" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "department" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "end_time" text,
  ADD COLUMN IF NOT EXISTS "from_balance_id" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "installation_required" text,
  ADD COLUMN IF NOT EXISTS "interested_products" text,
  ADD COLUMN IF NOT EXISTS "interested_products_names" text,
  ADD COLUMN IF NOT EXISTS "is_company_vehicle" text,
  ADD COLUMN IF NOT EXISTS "item_notes" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "max_stock" text,
  ADD COLUMN IF NOT EXISTS "min_stock" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "needed_date" text,
  ADD COLUMN IF NOT EXISTS "next_action" text,
  ADD COLUMN IF NOT EXISTS "next_visit_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "product_sku" text,
  ADD COLUMN IF NOT EXISTS "proposal_sent" text,
  ADD COLUMN IF NOT EXISTS "prospective_client_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "quantity" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "requester" text,
  ADD COLUMN IF NOT EXISTS "result" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "routes" text,
  ADD COLUMN IF NOT EXISTS "sale_date" text,
  ADD COLUMN IF NOT EXISTS "sale_price" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "selectedComponent" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "sequence" text,
  ADD COLUMN IF NOT EXISTS "serial_number" text,
  ADD COLUMN IF NOT EXISTS "sku" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "start_time" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "vehicle_km_end" text,
  ADD COLUMN IF NOT EXISTS "vehicle_km_start" text,
  ADD COLUMN IF NOT EXISTS "visit_date" text,
  ADD COLUMN IF NOT EXISTS "visit_report" text,
  ADD COLUMN IF NOT EXISTS "visit_type" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text,
  ADD COLUMN IF NOT EXISTS "warranty_months" text;

-- Tabela: ProductionOrder
ALTER TABLE public."ProductionOrder"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: ProductionRequest
ALTER TABLE public."ProductionRequest"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: ProductionRoute
ALTER TABLE public."ProductionRoute"
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "estimated_time" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "quantity" text,
  ADD COLUMN IF NOT EXISTS "resource_id" text,
  ADD COLUMN IF NOT EXISTS "resource_type" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "routes" text,
  ADD COLUMN IF NOT EXISTS "selectedComponent" text,
  ADD COLUMN IF NOT EXISTS "sequence" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: ProductionRouteStep
ALTER TABLE public."ProductionRouteStep"
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "estimated_time" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "resource_id" text,
  ADD COLUMN IF NOT EXISTS "resource_type" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "sequence" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: ProductionStep
ALTER TABLE public."ProductionStep"
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Tabela: ProspectionProjectItem
ALTER TABLE public."ProspectionProjectItem"
  ADD COLUMN IF NOT EXISTS "attachments" text,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "location_address" text,
  ADD COLUMN IF NOT EXISTS "location_latitude" text,
  ADD COLUMN IF NOT EXISTS "location_longitude" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "photos" text,
  ADD COLUMN IF NOT EXISTS "project_name" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "seller_name" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "voltage_type" text;

-- Tabela: ProspectionVisit
ALTER TABLE public."ProspectionVisit"
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "end_time" text,
  ADD COLUMN IF NOT EXISTS "interested_products" text,
  ADD COLUMN IF NOT EXISTS "interested_products_names" text,
  ADD COLUMN IF NOT EXISTS "is_company_vehicle" text,
  ADD COLUMN IF NOT EXISTS "next_action" text,
  ADD COLUMN IF NOT EXISTS "next_visit_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "proposal_sent" text,
  ADD COLUMN IF NOT EXISTS "prospective_client_name" text,
  ADD COLUMN IF NOT EXISTS "result" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "start_time" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "vehicle_km_end" text,
  ADD COLUMN IF NOT EXISTS "vehicle_km_start" text,
  ADD COLUMN IF NOT EXISTS "visit_date" text,
  ADD COLUMN IF NOT EXISTS "visit_report" text,
  ADD COLUMN IF NOT EXISTS "visit_type" text;

-- Tabela: Quote
ALTER TABLE public."Quote"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_name" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "seller_name" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "validity_date" text;

-- Tabela: QuoteAttachment
ALTER TABLE public."QuoteAttachment"
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: QuoteItem
ALTER TABLE public."QuoteItem"
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: QuoteSubitem
ALTER TABLE public."QuoteSubitem"
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: ReceivingBatch
ALTER TABLE public."ReceivingBatch"
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text;

-- Tabela: ReceivingItem
ALTER TABLE public."ReceivingItem"
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text;

-- Tabela: ReportTemplate
ALTER TABLE public."ReportTemplate"
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "format" text,
  ADD COLUMN IF NOT EXISTS "include_ai_insights" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "schedule_day_of_week" text,
  ADD COLUMN IF NOT EXISTS "schedule_enabled" text,
  ADD COLUMN IF NOT EXISTS "schedule_frequency" text,
  ADD COLUMN IF NOT EXISTS "schedule_time" text,
  ADD COLUMN IF NOT EXISTS "type" text;

-- Tabela: Reservation
ALTER TABLE public."Reservation"
  ADD COLUMN IF NOT EXISTS "carrier" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "nf_number" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "volume" text,
  ADD COLUMN IF NOT EXISTS "weight" text;

-- Tabela: Resource
ALTER TABLE public."Resource"
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "cost_per_hour" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "estimated_time" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "resource_id" text,
  ADD COLUMN IF NOT EXISTS "resource_type" text,
  ADD COLUMN IF NOT EXISTS "sequence" text,
  ADD COLUMN IF NOT EXISTS "type" text;

-- Tabela: Return
ALTER TABLE public."Return"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "condition" text,
  ADD COLUMN IF NOT EXISTS "item_notes" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "product_sku" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "reason_description" text,
  ADD COLUMN IF NOT EXISTS "return_date" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: ReturnItem
ALTER TABLE public."ReturnItem"
  ADD COLUMN IF NOT EXISTS "condition" text,
  ADD COLUMN IF NOT EXISTS "item_notes" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "product_sku" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text;

-- Tabela: SalesOrder
ALTER TABLE public."SalesOrder"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "carrier" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "contact_address" text,
  ADD COLUMN IF NOT EXISTS "contact_phone" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "installation_required" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "nf_number" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "reason_description" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "return_date" text,
  ADD COLUMN IF NOT EXISTS "sale_date" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "serial_number" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "volume" text,
  ADD COLUMN IF NOT EXISTS "warranty_months" text,
  ADD COLUMN IF NOT EXISTS "weight" text;

-- Tabela: SalesOrderItem
ALTER TABLE public."SalesOrderItem"
  ADD COLUMN IF NOT EXISTS "carrier" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "nf_number" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "volume" text,
  ADD COLUMN IF NOT EXISTS "weight" text;

-- Tabela: Seller
ALTER TABLE public."Seller"
  ADD COLUMN IF NOT EXISTS "attachments" text,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "commission_rate" text,
  ADD COLUMN IF NOT EXISTS "delivery_date" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "email" text,
  ADD COLUMN IF NOT EXISTS "end_time" text,
  ADD COLUMN IF NOT EXISTS "interested_products" text,
  ADD COLUMN IF NOT EXISTS "interested_products_names" text,
  ADD COLUMN IF NOT EXISTS "is_company_vehicle" text,
  ADD COLUMN IF NOT EXISTS "km_end" text,
  ADD COLUMN IF NOT EXISTS "km_start" text,
  ADD COLUMN IF NOT EXISTS "location_address" text,
  ADD COLUMN IF NOT EXISTS "location_latitude" text,
  ADD COLUMN IF NOT EXISTS "location_longitude" text,
  ADD COLUMN IF NOT EXISTS "log_date" text,
  ADD COLUMN IF NOT EXISTS "manager_ids" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "next_action" text,
  ADD COLUMN IF NOT EXISTS "next_visit_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_pedido_externo" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_id" text,
  ADD COLUMN IF NOT EXISTS "payment_condition_name" text,
  ADD COLUMN IF NOT EXISTS "phone" text,
  ADD COLUMN IF NOT EXISTS "photos" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "project_name" text,
  ADD COLUMN IF NOT EXISTS "proposal_sent" text,
  ADD COLUMN IF NOT EXISTS "prospective_client_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "result" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "seller_name" text,
  ADD COLUMN IF NOT EXISTS "start_time" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "validity_date" text,
  ADD COLUMN IF NOT EXISTS "vehicle_km_end" text,
  ADD COLUMN IF NOT EXISTS "vehicle_km_start" text,
  ADD COLUMN IF NOT EXISTS "visit_date" text,
  ADD COLUMN IF NOT EXISTS "visit_report" text,
  ADD COLUMN IF NOT EXISTS "visit_type" text,
  ADD COLUMN IF NOT EXISTS "voltage_type" text;

-- Tabela: SerialNumber
ALTER TABLE public."SerialNumber"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "installation_required" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "sale_date" text,
  ADD COLUMN IF NOT EXISTS "serial_number" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "warranty_months" text;

-- Tabela: ServiceOrder
ALTER TABLE public."ServiceOrder"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "contact_address" text,
  ADD COLUMN IF NOT EXISTS "contact_phone" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "diagnosis" text,
  ADD COLUMN IF NOT EXISTS "labor_cost" text,
  ADD COLUMN IF NOT EXISTS "labor_hours" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "parts_cost" text,
  ADD COLUMN IF NOT EXISTS "parts_used" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "serial_number" text,
  ADD COLUMN IF NOT EXISTS "solution" text,
  ADD COLUMN IF NOT EXISTS "type" text;

-- Tabela: ServiceRequest
ALTER TABLE public."ServiceRequest"
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "contact_address" text,
  ADD COLUMN IF NOT EXISTS "contact_phone" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "order_id" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "serial_number" text,
  ADD COLUMN IF NOT EXISTS "type" text;

-- Tabela: StockBalance
ALTER TABLE public."StockBalance"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "carrier" text,
  ADD COLUMN IF NOT EXISTS "cod_finame" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "from_balance_id" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "fulfill_mode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "nf_number" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "unit_price" text,
  ADD COLUMN IF NOT EXISTS "volume" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "weight" text;

-- Tabela: SystemConfiguration
ALTER TABLE public."SystemConfiguration"
  ADD COLUMN IF NOT EXISTS "auto_apply" text,
  ADD COLUMN IF NOT EXISTS "category" text,
  ADD COLUMN IF NOT EXISTS "config_id" text,
  ADD COLUMN IF NOT EXISTS "config_key" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "expected_value" text,
  ADD COLUMN IF NOT EXISTS "label" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "test_type" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "validation_rule" text;

-- Tabela: Technician
ALTER TABLE public."Technician"
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "diagnosis" text,
  ADD COLUMN IF NOT EXISTS "email" text,
  ADD COLUMN IF NOT EXISTS "labor_cost" text,
  ADD COLUMN IF NOT EXISTS "labor_hours" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "parts_cost" text,
  ADD COLUMN IF NOT EXISTS "parts_used" text,
  ADD COLUMN IF NOT EXISTS "phone" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "solution" text,
  ADD COLUMN IF NOT EXISTS "specialties" text;

-- Tabela: TechnicianHistory
ALTER TABLE public."TechnicianHistory"
  ADD COLUMN IF NOT EXISTS "diagnosis" text,
  ADD COLUMN IF NOT EXISTS "labor_cost" text,
  ADD COLUMN IF NOT EXISTS "labor_hours" text,
  ADD COLUMN IF NOT EXISTS "parts_cost" text,
  ADD COLUMN IF NOT EXISTS "parts_used" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "solution" text;

-- Tabela: User
ALTER TABLE public."User"
  ADD COLUMN IF NOT EXISTS "attachments" text,
  ADD COLUMN IF NOT EXISTS "city" text,
  ADD COLUMN IF NOT EXISTS "client_id" text,
  ADD COLUMN IF NOT EXISTS "client_name" text,
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "commission_rate" text,
  ADD COLUMN IF NOT EXISTS "description" text,
  ADD COLUMN IF NOT EXISTS "email" text,
  ADD COLUMN IF NOT EXISTS "end_time" text,
  ADD COLUMN IF NOT EXISTS "is_company_vehicle" text,
  ADD COLUMN IF NOT EXISTS "location_address" text,
  ADD COLUMN IF NOT EXISTS "location_latitude" text,
  ADD COLUMN IF NOT EXISTS "location_longitude" text,
  ADD COLUMN IF NOT EXISTS "manager_ids" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "next_action" text,
  ADD COLUMN IF NOT EXISTS "next_visit_date" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "phone" text,
  ADD COLUMN IF NOT EXISTS "photos" text,
  ADD COLUMN IF NOT EXISTS "project_name" text,
  ADD COLUMN IF NOT EXISTS "proposal_sent" text,
  ADD COLUMN IF NOT EXISTS "prospective_client_name" text,
  ADD COLUMN IF NOT EXISTS "result" text,
  ADD COLUMN IF NOT EXISTS "seller_id" text,
  ADD COLUMN IF NOT EXISTS "seller_name" text,
  ADD COLUMN IF NOT EXISTS "start_time" text,
  ADD COLUMN IF NOT EXISTS "state" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "visit_date" text,
  ADD COLUMN IF NOT EXISTS "visit_report" text,
  ADD COLUMN IF NOT EXISTS "visit_type" text,
  ADD COLUMN IF NOT EXISTS "voltage_type" text;

-- Tabela: Warehouse
ALTER TABLE public."Warehouse"
  ADD COLUMN IF NOT EXISTS "baixa_detalhamento" text,
  ADD COLUMN IF NOT EXISTS "baixa_motivo" text,
  ADD COLUMN IF NOT EXISTS "barcode" text,
  ADD COLUMN IF NOT EXISTS "capacity" text,
  ADD COLUMN IF NOT EXISTS "code" text,
  ADD COLUMN IF NOT EXISTS "cost_center_id" text,
  ADD COLUMN IF NOT EXISTS "due_date" text,
  ADD COLUMN IF NOT EXISTS "from_balance_id" text,
  ADD COLUMN IF NOT EXISTS "from_location_id" text,
  ADD COLUMN IF NOT EXISTS "from_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "location_barcode" text,
  ADD COLUMN IF NOT EXISTS "location_id" text,
  ADD COLUMN IF NOT EXISTS "manager_signature" text,
  ADD COLUMN IF NOT EXISTS "modulo" text,
  ADD COLUMN IF NOT EXISTS "name" text,
  ADD COLUMN IF NOT EXISTS "nivel" text,
  ADD COLUMN IF NOT EXISTS "notes" text,
  ADD COLUMN IF NOT EXISTS "numero_op_externo" text,
  ADD COLUMN IF NOT EXISTS "parent_op_id" text,
  ADD COLUMN IF NOT EXISTS "posicao" text,
  ADD COLUMN IF NOT EXISTS "priority" text,
  ADD COLUMN IF NOT EXISTS "product_id" text,
  ADD COLUMN IF NOT EXISTS "product_name" text,
  ADD COLUMN IF NOT EXISTS "qty" text,
  ADD COLUMN IF NOT EXISTS "qty_fulfilled" text,
  ADD COLUMN IF NOT EXISTS "qty_planned" text,
  ADD COLUMN IF NOT EXISTS "qty_requested" text,
  ADD COLUMN IF NOT EXISTS "qty_residue" text,
  ADD COLUMN IF NOT EXISTS "reason" text,
  ADD COLUMN IF NOT EXISTS "related_id" text,
  ADD COLUMN IF NOT EXISTS "related_type" text,
  ADD COLUMN IF NOT EXISTS "route_id" text,
  ADD COLUMN IF NOT EXISTS "route_name" text,
  ADD COLUMN IF NOT EXISTS "rua" text,
  ADD COLUMN IF NOT EXISTS "scheduled_date" text,
  ADD COLUMN IF NOT EXISTS "start_date" text,
  ADD COLUMN IF NOT EXISTS "status" text,
  ADD COLUMN IF NOT EXISTS "to_location_id" text,
  ADD COLUMN IF NOT EXISTS "to_warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "type" text,
  ADD COLUMN IF NOT EXISTS "unit_cost" text,
  ADD COLUMN IF NOT EXISTS "warehouse_id" text,
  ADD COLUMN IF NOT EXISTS "warehouse_name" text;

-- Recarrega cache do schema do PostgREST
NOTIFY pgrst, 'reload schema';
