export const LABEL_SIZES = {
  a4_4x6: {
    name: 'A4 - 4 por página (10x15cm)',
    cols: 2,
    rows: 2,
    width: '210mm',
    height: '297mm',
    itemWidth: '100mm',
    itemHeight: '148mm',
    padding: '5mm',
    gap: '0',
    qrSize: 70,
    fontSize: 'text-sm',
  },
  a4_8x10: {
    name: 'A4 - 8 por página',
    cols: 2,
    rows: 4,
    width: '210mm',
    height: '297mm',
    itemWidth: '100mm',
    itemHeight: '74mm',
    padding: '3mm',
    gap: '0',
    qrSize: 50,
    fontSize: 'text-xs',
  },
  a4_16: {
    name: 'A4 - 16 por página',
    cols: 4,
    rows: 4,
    width: '210mm',
    height: '297mm',
    itemWidth: '50mm',
    itemHeight: '74mm',
    padding: '2mm',
    gap: '0',
    qrSize: 35,
    fontSize: 'text-xs',
  },
  carta_4x6: {
    name: 'Carta (EUA) - 4x6 polegadas',
    cols: 2,
    rows: 3,
    width: '215.9mm',
    height: '279.4mm',
    itemWidth: '101.6mm',
    itemHeight: '88.9mm',
    padding: '3mm',
    gap: '2.5mm',
    qrSize: 60,
    fontSize: 'text-sm',
  },
  etiqueta_10x15: {
    name: 'Etiqueta 10x15cm (Rolo)',
    cols: 1,
    rows: 1,
    width: '100mm',
    height: '150mm',
    itemWidth: '100mm',
    itemHeight: '150mm',
    padding: '5mm',
    gap: '0',
    qrSize: 80,
    fontSize: 'text-base',
  },
};